import "./globals.scss";
import type { Metadata } from "next";

//font
import { Noto_Sans_JP } from "next/font/google";

const nsjp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={nsjp.className}>{children}</body>
    </html>
  );
}
